In [4]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.width', 1000)

In [5]:
customers = pd.read_csv("data/customers.csv")
locations = pd.read_csv("data/locations.csv")
products = pd.read_csv("data/products.csv")
orders = pd.read_csv("data/orders.csv")
order_items = pd.read_csv("data/order_items.csv")
payments = pd.read_csv("data/payments.csv")
shipping = pd.read_csv("data/shipping.csv")
returns = pd.read_csv("data/returns.csv")
reviews = pd.read_csv("data/reviews.csv")

# Customers Analysis

In [6]:
print(customers.head())

   customer_id customer_name  gender   age  location_id signup_date customer_segment
0        10001  Kiran Sharma   Other  51.0           37  2022-01-25          Regular
1        10002  Aarav Sharma    Male  57.0           83  2024-02-01          Premium
2        10003  Aanya Sharma  Female  58.0            1  2025-06-09          Regular
3        10004  Ananya Patel  Female  28.0           90  2025-12-07          Regular
4        10005  Vihaan Patel    Male  38.0           55  2023-04-13          Regular

In [7]:
print(customers.shape)

(5000, 7)

In [8]:
print(customers.columns)

Index(['customer_id', 'customer_name', 'gender', 'age', 'location_id', 'signup_date', 'customer_segment'], dtype='str')

In [9]:
print(customers.info())

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       5000 non-null   int64
 1   customer_name     5000 non-null   str
 2   gender            5000 non-null   str
 3   age               4990 non-null   float64
 4   location_id       5000 non-null   int64
 5   signup_date       5000 non-null   str
 6   customer_segment  5000 non-null   str
dtypes: float64(1), int64(2), str(4)
memory usage: 273.6 KB
None

In [10]:
print(customers.isnull().sum())

customer_id          0
customer_name        0
gender               0
age                 10
location_id          0
signup_date          0
customer_segment     0
dtype: int64

In [11]:
print(customers.duplicated().sum())

0

In [12]:
print(customers["customer_segment"].unique())
print(customers["customer_segment"].value_counts())

<StringArray>
['Regular', 'Premium', 'VIP']
Length: 3, dtype: str
customer_segment
Regular    3371
Premium    1264
VIP         365
Name: count, dtype: int64

In [13]:
customers.columns = customers.columns.str.strip()
print(customers.columns)

Index(['customer_id', 'customer_name', 'gender', 'age', 'location_id', 'signup_date', 'customer_segment'], dtype='str')

In [14]:
# Check unique values in categorical columns 

print("Gender:")
print(customers["gender"].unique())

print("\ncustomer Segment:")
print(customers["customer_segment"].unique())

Gender:
<StringArray>
['Other', 'Male', 'Female', 'FEMALE', ' male', ' other ']
Length: 6, dtype: str

customer Segment:
<StringArray>
['Regular', 'Premium', 'VIP']
Length: 3, dtype: str

In [15]:
# Check text consistency in categorical columns 

print("gender values:")
print(customers["gender"].value_counts(dropna=False))

print("\ncustomer segment values:")
print(customers["customer_segment"].value_counts(dropna=False))

gender values:
gender
Male       2636
Female     2243
Other       101
 male        11
FEMALE        8
 other        1
Name: count, dtype: int64

customer segment values:
customer_segment
Regular    3371
Premium    1264
VIP         365
Name: count, dtype: int64

In [16]:
# check for leading and trailing spaces in customer_name
print("Names with leading/trailing spaces:")
print(customers[customers["customer_name"] != customers["customer_name"].str.strip()])

Names with leading/trailing spaces:
Empty DataFrame
Columns: [customer_id, customer_name, gender, age, location_id, signup_date, customer_segment]
Index: []

In [17]:
# Check for multiple spaces inside customer names
print(customers[customers["customer_name"].str.contains(r"\s{2,}", na=False)])

Empty DataFrame
Columns: [customer_id, customer_name, gender, age, location_id, signup_date, customer_segment]
Index: []

In [18]:
# Date Validation 
print(customers["signup_date"].dtype)

str

In [19]:
# Check earliest and latest signup dates
print("Earliest signup date:", customers["signup_date"].min())
print("Latest signup date:", customers["signup_date"].max())

Earliest signup date: 2022-01-01
Latest signup date: 2026-05-19

In [20]:
# Check age statistics
print(customers["age"].describe())

count    4990.000000
mean       41.291784
std        13.919529
min        18.000000
25%        29.000000
50%        41.000000
75%        53.000000
max        65.000000
Name: age, dtype: float64

In [21]:
# Find potentially unrealstics customer ages 
print(customers[(customers ["age"] < 18) | (customers["age"] > 80)])

Empty DataFrame
Columns: [customer_id, customer_name, gender, age, location_id, signup_date, customer_segment]
Index: []

In [22]:
# Check frequency of each age 
print(customers["age"].value_counts().sort_index())

age
18.0    123
19.0    132
20.0     94
21.0    100
22.0     87
23.0    100
24.0    104
25.0    106
26.0    108
27.0    105
28.0    121
29.0    106
30.0    103
31.0     90
32.0    118
33.0     87
34.0    105
35.0    107
36.0    117
37.0    119
38.0    102
39.0    105
40.0     91
41.0     86
42.0     98
43.0    102
44.0    104
45.0    110
46.0    103
47.0     93
48.0     96
49.0    111
50.0    108
51.0    131
52.0    103
53.0    107
54.0     92
55.0    114
56.0    102
57.0     93
58.0     92
59.0    107
60.0     78
61.0     91
62.0    105
63.0    118
64.0    122
65.0     94
Name: count, dtype: int64

In [23]:
customers[customers["age"].isna()]

      customer_id        customer_name  gender  age  location_id signup_date customer_segment
43          10044           Aman Patel   Other  NaN           52  2023-05-24          Regular
1235        11236           Vivek Iyer    Male  NaN            4  2023-11-19          Regular
1250        11251         Mohit Tiwari    Male  NaN           29  2022-05-02          Regular
1701        11702          Harsh Reddy    Male  NaN            7  2025-07-08          Premium
2264        12265    Sahil Bansal 1313    Male  NaN           44  2024-01-20          Regular
2803        12804      Rahul Khan 1606    Male  NaN           44  2025-10-08          Regular
3207        13208     Dhruv Sinha 1803    Male  NaN           82  2024-06-26          Regular
3649        13650  Radhika Pillai 1708  Female  NaN           18  2022-06-16          Regular
4174        14175   Muskan Bansal 1950  Female  NaN           86  2025-01-25          Regular
4895        14896      Aman Arora 2687    Male  NaN           41  2023-11-07          Regular

 Cleaning customers

In [24]:
'''Age contains 10 missing values;
   retained as NULL because no reliable source was available for imputation.'''

'Age contains 10 missing values;\n   retained as NULL because no reliable source was available for imputation.'

In [25]:
# Standardize gender values 

customers["gender"] = customers["gender"].str.strip().str.title()
print(customers["gender"].value_counts(dropna=False))

gender
Male      2647
Female    2251
Other      102
Name: count, dtype: int64

In [26]:
# Convert signup_date from string to datetime 

customers["signup_date"] = pd.to_datetime(customers["signup_date"], dayfirst=True)
print(customers["signup_date"].dtype)

datetime64[us]

C:\Users\user\AppData\Local\Temp\ipykernel_8564\3723815062.py:3: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  customers["signup_date"] = pd.to_datetime(customers["signup_date"], dayfirst=True)

# locations Analysis

In [27]:
print(locations.head())

   location_id     city           state country   region
0            1   Mumbai     Maharashtra   India     West
1            2    Patna           Bihar   India     East
2            3   Indore  Madhya Pradesh   India  Central
3            4  Lucknow   Uttar Pradesh   India    North
4            5  Lucknow   Uttar Pradesh   India    North

In [28]:
print(locations.shape)

(100, 5)

In [29]:
print(locations.info())

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   location_id  100 non-null    int64
 1   city         100 non-null    str
 2   state        100 non-null    str
 3   country      100 non-null    str
 4   region       100 non-null    str
dtypes: int64(1), str(4)
memory usage: 4.0 KB
None

In [30]:
print(locations.isnull().sum())

location_id    0
city           0
state          0
country        0
region         0
dtype: int64

In [31]:
print(locations.duplicated().sum())

0

In [32]:
print(locations["region"].unique())
print(locations["region"].value_counts())

<StringArray>
['West', 'East', 'Central', 'North', 'South']
Length: 5, dtype: str
region
North      29
West       23
South      20
Central    17
East       11
Name: count, dtype: int64

In [33]:
# Check for leading amd trailing spaces 

print("city with leading/trailing spaces:")
print(locations[locations["city"] != locations["city"].str.strip()])

print("\nstate with leading/trailing spaces")
print(locations[locations["state"] != locations["state"].str.strip()])

print("\ncountry with leading/trailing spaces")
print(locations[locations["country"] != locations["country"].str.strip()])

city with leading/trailing spaces:
Empty DataFrame
Columns: [location_id, city, state, country, region]
Index: []

state with leading/trailing spaces
Empty DataFrame
Columns: [location_id, city, state, country, region]
Index: []

country with leading/trailing spaces
Empty DataFrame
Columns: [location_id, city, state, country, region]
Index: []

In [34]:
# check for multiple spaces 

print("Multiple spaces inside city")
print(locations[locations["city"].str.contains(r"\s{2,}", na=False)])

print("\nMultiple spaces inside state")
print(locations[locations["state"].str.contains(r"\s{2,}", na=False)])

print("\nMultiple spaces inside country")
print(locations[locations['country'].str.contains(r"\s{2,}", na=False)])

Multiple spaces inside city
Empty DataFrame
Columns: [location_id, city, state, country, region]
Index: []

Multiple spaces inside state
Empty DataFrame
Columns: [location_id, city, state, country, region]
Index: []

Multiple spaces inside country
Empty DataFrame
Columns: [location_id, city, state, country, region]
Index: []

In [35]:
# Check city, state , country and region combinations

locations[["city", "state", "country"]].drop_duplicates().sort_values("city")

          city           state country
19   Ahmedabad         Gujarat   India
17   Bengaluru       Karnataka   India
12      Bhopal  Madhya Pradesh   India
25  Chandigarh      Chandigarh   India
8      Chennai      Tamil Nadu   India
55       Delhi           Delhi   India
33    Gurugram         Haryana   India
22   Hyderabad       Telangana   India
2       Indore  Madhya Pradesh   India
21      Jaipur       Rajasthan   India
11      Kanpur   Uttar Pradesh   India
18       Kochi          Kerala   India
38     Kolkata     West Bengal   India
3      Lucknow   Uttar Pradesh   India
0       Mumbai     Maharashtra   India
23      Nagpur     Maharashtra   India
10       Noida   Uttar Pradesh   India
1        Patna           Bihar   India
65        Pune     Maharashtra   India
5        Surat         Gujarat   India

In [36]:
# Check whether each city has only one state and one region

city_mapping_check = (
    locations.groupby("city")[["state", "region"]].nunique()
)
city_mapping_check

            state  region
city
Ahmedabad       1       1
Bengaluru       1       1
Bhopal          1       1
Chandigarh      1       1
Chennai         1       1
Delhi           1       1
Gurugram        1       1
Hyderabad       1       1
Indore          1       1
Jaipur          1       1
Kanpur          1       1
Kochi           1       1
Kolkata         1       1
Lucknow         1       1
Mumbai          1       1
Nagpur          1       1
Noida           1       1
Patna           1       1
Pune            1       1
Surat           1       1

# Products Analysis

In [37]:
print(products.head())

   product_id         product_name     category sub_category      brand  unit_price_inr  cost_price_inr stock_status
0       20001       Tab Series 001  Electronics       Tablet   HomeEase          2864.0          1865.0    Low Stock
1       20002     Pulse Series 002  Electronics   Smartwatch  UrbanCart          1249.0           815.0     In Stock
2       20003    Summit Series 003       Sports      Outdoor       Apex           620.0           354.0     In Stock
3       20004  Boundary Series 004       Sports      Cricket     FitMax           657.0           497.0     In Stock
4       20005     Clear Series 005       Beauty     Skincare   HomeEase          1453.0           819.0     In Stock

In [38]:
print(products.shape)

(1500, 8)

In [39]:
print(products.info())

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      1500 non-null   int64
 1   product_name    1500 non-null   str
 2   category        1500 non-null   str
 3   sub_category    1500 non-null   str
 4   brand           1496 non-null   str
 5   unit_price_inr  1500 non-null   float64
 6   cost_price_inr  1500 non-null   float64
 7   stock_status    1497 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 93.9 KB
None

In [40]:
print(products.isnull().sum())

product_id        0
product_name      0
category          0
sub_category      0
brand             4
unit_price_inr    0
cost_price_inr    0
stock_status      3
dtype: int64

In [41]:
print(products.duplicated().sum())

0

In [42]:
print(products["category"].unique())
print(products["category"].value_counts())

<StringArray>
['Electronics', 'Sports', 'Beauty', 'Home & Kitchen', 'Books', 'Fashion']
Length: 6, dtype: str
category
Fashion           280
Home & Kitchen    255
Beauty            245
Electronics       242
Books             242
Sports            236
Name: count, dtype: int64

In [43]:
# Check for leading and trailing spaces

print("product_name with leading and trailing spaces")
print(products[products["product_name"] != products["product_name"].str.strip()])

print("\nCategory with leading and trailing spaces ")
print(products[products["category"] != products["category"].str.strip()])

print("\nsub_category with leading and trailing spaces")
print(products[products["sub_category"] != products["sub_category"].str.strip()])

print("\nbrand  with leading and trailing spaces")
print(products[products["brand"] != products["brand"].str.strip()])

print("\nstock_status with leading and trailing spaces")
print(products[products["stock_status"] != products["stock_status"].str.strip()])

product_name with leading and trailing spaces
Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

Category with leading and trailing spaces
Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

sub_category with leading and trailing spaces
Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

brand  with leading and trailing spaces
      product_id        product_name        category sub_category brand  unit_price_inr  cost_price_inr stock_status
17         20018       Steel Pro 018  Home & Kitchen     Cookware   NaN           934.0           750.0     In Stock
390        20391       Trail Pro 141          Sports      Outdoor   NaN          2428.0          1620.0     In Stock
811        20812       Home Lite 062  Home & Kitchen   Appliances   NaN           815.0           529.0     In Stock
1156       21157  Wonder Advance 157           Books     Children   NaN          1088.0           884.0     In Stock

stock_status with leading and trailing spaces
      product_id         product_name        category sub_category      brand  unit_price_inr  cost_price_inr stock_status
555        20556  Mystery Advance 056           Books      Fiction   HomeEase          1700.0          1392.0          NaN
1161       21162      Sound Elite 162     Electronics   Headphones    TechPro          1557.0          1271.0          NaN
1254       21255       Living Max 005  Home & Kitchen        Decor  PrimeLine          1438.0           848.0          NaN

In [44]:
# Check for multiple spaces

print("multiple spaces inside product_name")
print(products[products["product_name"].str.contains(r"\s{2,}", na=False)])

print("\nmultiple spaces inside category")
print(products[products["category"].str.contains(r"\s{2,}", na=False)])

print("\nmultiple spaces inside sub_catgeory")
print(products[products["sub_category"].str.contains(r"\s{2,}", na=False)])

print("\nmultiple spaces inside brnad")
print(products[products["brand"].str.contains(r"\s{2,}", na=False)])

print("\nmultiple spaces inside stock_status")
print(products[products["stock_status"].str.contains(r"\s{2,}", na=False)])

multiple spaces inside product_name
Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

multiple spaces inside category
Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

multiple spaces inside sub_catgeory
Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

multiple spaces inside brnad
Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

multiple spaces inside stock_status
Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

In [45]:
print(products["unit_price_inr"].isna().sum())

0

In [46]:
print(products[products['unit_price_inr'] <=0])

Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

In [47]:
print(products.describe())

         product_id  unit_price_inr  cost_price_inr
count   1500.000000     1500.000000     1500.000000
mean   20750.500000     1720.814667     1204.532667
std      433.157015     1258.597942      932.491053
min    20001.000000      178.000000      118.000000
25%    20375.750000      882.500000      601.500000
50%    20750.500000     1357.000000      952.000000
75%    21125.250000     2164.000000     1493.750000
max    21500.000000    13516.000000    10505.000000

In [48]:
# check outliers 
print("outliers in unit_price_inr")
print(products["unit_price_inr"].quantile([0.01, 0.25, 0.50, 0.75,0.99]))

print("\noutliers in cost_price_inr")
print(products["cost_price_inr"].quantile([0.01,0.25,0.50,0.75,0.99]))

outliers in unit_price_inr
0.01     310.87
0.25     882.50
0.50    1357.00
0.75    2164.00
0.99    6637.32
Name: unit_price_inr, dtype: float64

outliers in cost_price_inr
0.01     203.99
0.25     601.50
0.50     952.00
0.75    1493.75
0.99    4563.34
Name: cost_price_inr, dtype: float64

In [49]:
print(products[products["cost_price_inr"] <=0])

Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

In [50]:
# Check for unit price vs cost price
print(products[products["unit_price_inr"] < products["cost_price_inr"]])

Empty DataFrame
Columns: [product_id, product_name, category, sub_category, brand, unit_price_inr, cost_price_inr, stock_status]
Index: []

cleaning products

In [51]:
products[products["brand"].isna()]

      product_id        product_name        category sub_category brand  unit_price_inr  cost_price_inr stock_status
17         20018       Steel Pro 018  Home & Kitchen     Cookware   NaN           934.0           750.0     In Stock
390        20391       Trail Pro 141          Sports      Outdoor   NaN          2428.0          1620.0     In Stock
811        20812       Home Lite 062  Home & Kitchen   Appliances   NaN           815.0           529.0     In Stock
1156       21157  Wonder Advance 157           Books     Children   NaN          1088.0           884.0     In Stock

In [52]:
products[products['brand'].isna()][['product_id', 'product_name']]

      product_id        product_name
17         20018       Steel Pro 018
390        20391       Trail Pro 141
811        20812       Home Lite 062
1156       21157  Wonder Advance 157

In [53]:
products[products["product_name"].isin(products.loc[products["brand"].isna(), "product_name"]
)][["product_id", "product_name", "brand"]]

      product_id        product_name brand
17         20018       Steel Pro 018   NaN
390        20391       Trail Pro 141   NaN
811        20812       Home Lite 062   NaN
1156       21157  Wonder Advance 157   NaN

In [54]:
# fill null values in brand

products['brand'] = products['brand'].fillna('Unknown')

print(products["brand"].isna().sum())
products["brand"].value_counts()

0

brand
HomeEase     202
FitMax       199
Apex         195
UrbanCart    190
TechPro      182
StyleHub     179
PrimeLine    175
Nova         174
Unknown        4
Name: count, dtype: int64

In [55]:
products[products['stock_status'].isna()]

      product_id         product_name        category sub_category      brand  unit_price_inr  cost_price_inr stock_status
555        20556  Mystery Advance 056           Books      Fiction   HomeEase          1700.0          1392.0          NaN
1161       21162      Sound Elite 162     Electronics   Headphones    TechPro          1557.0          1271.0          NaN
1254       21255       Living Max 005  Home & Kitchen        Decor  PrimeLine          1438.0           848.0          NaN

In [56]:
products[products['stock_status'].isna()][
    ['product_id', 'product_name', 'category', 'sub_category', 'brand']
]

      product_id         product_name        category sub_category      brand
555        20556  Mystery Advance 056           Books      Fiction   HomeEase
1161       21162      Sound Elite 162     Electronics   Headphones    TechPro
1254       21255       Living Max 005  Home & Kitchen        Decor  PrimeLine

In [57]:
missing = products[products['stock_status'].isna()]

for _, row in missing.iterrows():
    print("\n", row['product_name'], "|", row['category'], "|", row['sub_category'])
    print(
        products[
            (products['category'] == row['category']) &
            (products['sub_category'] == row['sub_category'])
        ]['stock_status'].value_counts(dropna=False)
    )

 Mystery Advance 056 | Books | Fiction
stock_status
In Stock        37
Low Stock       12
Out of Stock     3
NaN              1
Name: count, dtype: int64

 Sound Elite 162 | Electronics | Headphones
stock_status
In Stock        24
Low Stock        6
Out of Stock     2
NaN              1
Name: count, dtype: int64

 Living Max 005 | Home & Kitchen | Decor
stock_status
In Stock        33
Low Stock        7
Out of Stock     1
NaN              1
Name: count, dtype: int64

In [58]:
# Fill missing stock_status using the majority status
# within the corresponding category and sub_category group

products.loc[products["stock_status"].isna(), "stock_status"] = "In Stock"

In [59]:
# standerdize stock_status values

products["stock_status"] = products["stock_status"].str.strip().str.title()
print(products["stock_status"].value_counts(dropna=False))

stock_status
In Stock        1171
Low Stock        275
Out Of Stock      54
Name: count, dtype: int64

In [60]:
print(products["stock_status"].isna().sum())
print(products["stock_status"].value_counts())

0
stock_status
In Stock        1171
Low Stock        275
Out Of Stock      54
Name: count, dtype: int64

# orders Analysis

In [61]:
print(orders.head())

   order_id  customer_id  order_date order_status sales_channel coupon_code
0     50001        11745  2026-04-25    Cancelled       Website        NONE
1     50002        14533  2025-05-20    Delivered    Mobile App        NONE
2     50003        13164  2024-10-29    Delivered       Website        NONE
3     50004        12458  2024-03-21      Shipped       Website      FEST15
4     50005        11656  2024-10-26    Delivered       Website        NONE

In [62]:
print(orders.shape)

(20000, 6)

In [63]:
print(orders.info())

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       20000 non-null  int64
 1   customer_id    20000 non-null  int64
 2   order_date     20000 non-null  str
 3   order_status   20000 non-null  str
 4   sales_channel  20000 non-null  str
 5   coupon_code    19940 non-null  str
dtypes: int64(2), str(4)
memory usage: 937.6 KB
None

In [64]:
print(orders.isnull().sum())

order_id          0
customer_id       0
order_date        0
order_status      0
sales_channel     0
coupon_code      60
dtype: int64

In [65]:
print(orders.duplicated().sum())

0

In [66]:
print(orders["order_status"].unique())

<StringArray>
['Cancelled', 'Delivered', 'Shipped', 'Processing']
Length: 4, dtype: str

In [67]:
print(orders["sales_channel"].unique())

<StringArray>
['Website', 'Mobile App', 'Marketplace', ' marketplace', 'Mobile app ', 'website']
Length: 6, dtype: str

In [68]:
orders["sales_channel"].value_counts(dropna=False)

sales_channel
Website         9881
Mobile App      7027
Marketplace     3012
website           40
Mobile app        25
 marketplace      15
Name: count, dtype: int64

In [69]:
print(orders["coupon_code"].unique())

<StringArray>
['NONE', 'FEST15', 'SAVE10', 'BIG20', 'WELCOME5', nan]
Length: 6, dtype: str

In [70]:
orders["coupon_code"].value_counts(dropna=False)

coupon_code
NONE        10875
SAVE10       3232
FEST15       2364
WELCOME5     2039
BIG20        1430
NaN            60
Name: count, dtype: int64

In [71]:
# leading and trailing spaces 

print("order_status with leading and trailing spaces")
print(orders[orders["order_status"] != orders["order_status"].str.strip()])

print("\nsales_channel with leading and trailing spaces")
print(orders[orders["sales_channel"] != orders["sales_channel"].str.strip()])

print("\ncupon_code with leading and trailing spaces")
print(orders[orders["coupon_code"] != orders["coupon_code"].str.strip()])

order_status with leading and trailing spaces
Empty DataFrame
Columns: [order_id, customer_id, order_date, order_status, sales_channel, coupon_code]
Index: []

sales_channel with leading and trailing spaces
       order_id  customer_id  order_date order_status sales_channel coupon_code
207       50208        11553  2025-08-12    Delivered   marketplace      FEST15
251       50252        12694  2026-02-10    Delivered   marketplace        NONE
792       50793        13073  2024-11-28      Shipped   Mobile app        BIG20
953       50954        11836  2024-08-14    Delivered   Mobile app       SAVE10
2612      52613        13688  2025-03-04      Shipped   Mobile app         NONE
2831      52832        10556  2025-09-05    Delivered   Mobile app         NONE
3434      53435        11905  2025-03-19    Delivered   Mobile app         NONE
3789      53790        12366  2024-11-02    Delivered   Mobile app       SAVE10
3890      53891        10414  2024-11-22    Delivered   Mobile app         NONE
4003      54004        10137  2024-11-06      Shipped   Mobile app        BIG20
4422      54423        10870  2025-09-04    Delivered   Mobile app       SAVE10
4531      54532        10311  2026-07-06    Delivered   marketplace        NONE
4557      54558        13937  2026-04-02    Delivered   Mobile app       SAVE10
5299      55300        11548  2025-09-03    Delivered   marketplace        NONE
5432      55433        13331  2024-03-06    Cancelled   Mobile app         NONE
6341      56342        10122  2024-01-21    Delivered   marketplace        NONE
6577      56578        10601  2024-10-30    Delivered   marketplace    WELCOME5
6750      56751        13390  2025-06-19    Delivered   Mobile app         NONE
6934      56935        12789  2024-10-13      Shipped   marketplace        NONE
7740      57741        12621  2025-06-30    Delivered   marketplace        NONE
8442      58443        12782  2024-10-27    Delivered   Mobile app       SAVE10
8705      58706        12516  2025-01-24    Delivered   Mobile app       SAVE10
8755      58756        10332  2024-03-02    Delivered   marketplace      FEST15
9000      59001        10451  2026-04-16    Delivered   Mobile app       FEST15
9892      59893        13706  2026-01-02   Processing   marketplace      FEST15
10374     60375        14602  2026-05-05    Delivered   marketplace        NONE
10505     60506        14217  2024-12-01    Delivered   marketplace        NONE
11358     61359        13731  2024-11-10      Shipped   Mobile app     WELCOME5
12901     62902        12875  2025-12-05    Delivered   Mobile app         NONE
13355     63356        14616  2024-04-01      Shipped   marketplace        NONE
13544     63545        13725  2025-10-25      Shipped   Mobile app         NONE
13896     63897        10190  2024-09-24      Shipped   Mobile app         NONE
14805     64806        14422  2026-04-03    Delivered   Mobile app       SAVE10
15029     65030        14772  2024-02-02    Delivered   Mobile app       SAVE10
15973     65974        11732  2026-01-03    Delivered   Mobile app       FEST15
17051     67052        10786  2026-03-25    Delivered   marketplace        NONE
18561     68562        14288  2026-03-04    Delivered   Mobile app         NONE
18613     68614        10331  2024-11-10    Delivered   Mobile app       SAVE10
19115     69116        13019  2025-02-15    Delivered   Mobile app     WELCOME5
19824     69825        14214  2025-11-23    Delivered   marketplace    WELCOME5

cupon_code with leading and trailing spaces
       order_id  customer_id  order_date order_status sales_channel coupon_code
62        50063        14107  2025-12-16    Cancelled    Mobile App         NaN
243       50244        10604  2026-05-21    Delivered    Mobile App         NaN
588       50589        11037  2025-12-07    Delivered    Mobile App         NaN
621       50622        13849  2025-06-02    Delivered       Website         NaN
798       50799        11664  2025-09-25    Delivered    Mobile App         NaN
1415      51416        14018  2026-05-25    Delivered       Website         NaN
2049      52050        14920  2026-02-14    Delivered       Website         NaN
2069      52070        13957  2025-02-16    Delivered    Mobile App         NaN
2145      52146        14579  2025-01-22    Delivered   Marketplace         NaN
2233      52234        11170  2026-03-25    Delivered    Mobile App         NaN
2476      52477        12570  2024-03-15    Delivered    Mobile App         NaN
3332      53333        14955  2026-03-23    Delivered       Website         NaN
4445      54446        14910  2025-12-01      Shipped    Mobile App         NaN
4709      54710        12311  2025-10-16      Shipped    Mobile App         NaN
4829      54830        11714  2024-07-27    Delivered    Mobile App         NaN
5149      55150        13667  2025-07-29      Shipped       Website         NaN
6069      56070        13289  2024-10-14    Delivered    Mobile App         NaN
6079      56080        12191  2025-04-19    Delivered   Marketplace         NaN
6130      56131        12915  2025-11-10    Delivered       Website         NaN
6240      56241        13431  2025-10-22    Delivered    Mobile App         NaN
6982      56983        13120  2025-12-10    Delivered   Marketplace         NaN
7171      57172        14070  2024-07-13    Delivered       Website         NaN
7192      57193        14631  2024-05-04      Shipped       Website         NaN
7302      57303        14004  2024-10-28    Delivered    Mobile App         NaN
7345      57346        11656  2025-07-06    Delivered    Mobile App         NaN
7515      57516        13471  2024-01-27      Shipped       Website         NaN
7682      57683        14390  2024-08-06    Delivered       Website         NaN
7778      57779        11596  2026-07-16    Delivered       Website         NaN
8293      58294        12070  2024-01-04    Delivered       Website         NaN
8788      58789        11921  2026-06-25    Delivered       Website         NaN
8890      58891        13124  2026-06-08      Shipped    Mobile App         NaN
9035      59036        12210  2025-04-18    Delivered       Website         NaN
9136      59137        11251  2026-04-20    Delivered    Mobile App         NaN
9346      59347        13888  2026-04-04    Delivered       Website         NaN
10545     60546        11770  2024-05-18    Delivered    Mobile App         NaN
11326     61327        10110  2025-07-20    Delivered    Mobile App         NaN
11678     61679        11005  2024-09-16    Delivered       Website         NaN
11791     61792        11586  2025-09-02   Processing       Website         NaN
12826     62827        11262  2025-06-19    Delivered       Website         NaN
13116     63117        11563  2025-05-08    Delivered    Mobile App         NaN
13138     63139        11700  2024-11-08      Shipped       Website         NaN
13935     63936        12303  2026-06-14    Delivered    Mobile App         NaN
14216     64217        12764  2025-03-15    Delivered   Marketplace         NaN
14816     64817        12966  2024-06-06      Shipped       Website         NaN
15402     65403        10342  2024-08-13    Delivered       Website         NaN
15646     65647        12540  2024-05-26      Shipped    Mobile App         NaN
15757     65758        12703  2026-03-17      Shipped   Marketplace         NaN
15842     65843        12243  2026-08-03    Delivered       Website         NaN
15863     65864        14145  2026-02-19    Delivered    Mobile App         NaN
15882     65883        12796  2026-04-10    Delivered    Mobile App         NaN
15943     65944        14043  2026-07-16      Shipped       Website         NaN
16029     66030        10384  2024-01-15    Delivered    Mobile App         NaN
16446     66447        13284  2024-10-11    Delivered       Website         NaN
16815     66816        13665  2025-08-14    Delivered   Marketplace         NaN
17061     67062        10400  2024-06-05    Delivered       Website         NaN
17542     67543        12418  2024-06-14      Shipped    Mobile App         NaN
17559     67560        12403  2026-01-03    Delivered       Website         NaN
17685     67686        14533  2024-10-28    Delivered    Mobile App         NaN
18924     68925        10837  2026-02-13    Delivered    Mobile App         NaN
19850     69851        10291  2024-12-15    Delivered       Website         NaN

In [72]:
# check for double spaces 


print("Multiple spaces inside order_status:")
print(orders[orders["order_status"].str.contains(r"\s{2,}", na=False)])

print("\nMultiple spaces inside sales_channel:")
print(orders[orders["sales_channel"].str.contains(r"\s{2,}", na=False)])

print("\nMultiple spaces inside coupon_code:")
print(orders[orders["coupon_code"].str.contains(r"\s{2,}", na=False)])

Multiple spaces inside order_status:
Empty DataFrame
Columns: [order_id, customer_id, order_date, order_status, sales_channel, coupon_code]
Index: []

Multiple spaces inside sales_channel:
Empty DataFrame
Columns: [order_id, customer_id, order_date, order_status, sales_channel, coupon_code]
Index: []

Multiple spaces inside coupon_code:
Empty DataFrame
Columns: [order_id, customer_id, order_date, order_status, sales_channel, coupon_code]
Index: []

In [73]:
print(orders["order_date"].dtype)

str

In [74]:
print("Earliest order_date:", orders["order_date"].min())
print("Latest order_date:", orders["order_date"].max())

Earliest order_date: 2024-01-01
Latest order_date: 2026-11-01

Cleaning orders

In [75]:
# Fill coupon_code with with the majority coupon_code

orders.loc[orders["coupon_code"].isna(), "coupon_code"] = "NONE"

In [76]:
# Standerdize coupon code values 

orders["coupon_code"]=orders["coupon_code"].str.strip().str.title()
print(orders["coupon_code"].value_counts(dropna=False))

coupon_code
None        10935
Save10       3232
Fest15       2364
Welcome5     2039
Big20        1430
Name: count, dtype: int64

In [77]:
# staderdize sales_channel values 

orders["sales_channel"] = orders["sales_channel"].str.strip().str.title()
print(orders["sales_channel"].value_counts(dropna=False))

sales_channel
Website        9921
Mobile App     7052
Marketplace    3027
Name: count, dtype: int64

In [78]:

orders["order_date"] = pd.to_datetime(orders["order_date"], dayfirst=True)
print(orders["order_date"].dtype)

datetime64[us]

C:\Users\user\AppData\Local\Temp\ipykernel_8564\829913886.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  orders["order_date"] = pd.to_datetime(orders["order_date"], dayfirst=True)

# order_items analysis

In [79]:
print(order_items.head())

   order_item_id  order_id  product_id  quantity  unit_price_inr  discount_pct  line_sales_inr  line_cost_inr
0          90001     50001       20027         2           552.0             0          1104.0          624.0
1          90002     50002       20869         2           423.0             5           803.7          596.0
2          90003     50003       20330         1          3108.0             5          2952.6         1905.0
3          90004     50004       20979         4           819.0             5          3112.2         2168.0
4          90005     50005       21125         1           872.0             0           872.0          720.0

In [80]:
print(order_items.shape)

(30931, 8)

In [81]:
print(order_items.info())

<class 'pandas.DataFrame'>
RangeIndex: 30931 entries, 0 to 30930
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_item_id   30931 non-null  int64
 1   order_id        30931 non-null  int64
 2   product_id      30931 non-null  int64
 3   quantity        30931 non-null  int64
 4   unit_price_inr  30931 non-null  float64
 5   discount_pct    30931 non-null  int64
 6   line_sales_inr  30931 non-null  float64
 7   line_cost_inr   30931 non-null  float64
dtypes: float64(3), int64(5)
memory usage: 1.9 MB
None

In [82]:
print(order_items.isnull().sum())

order_item_id     0
order_id          0
product_id        0
quantity          0
unit_price_inr    0
discount_pct      0
line_sales_inr    0
line_cost_inr     0
dtype: int64

In [83]:
print(order_items.duplicated().sum())

0

In [84]:
# check for negative value 
order_items[order_items < 0].count()

order_item_id     0
order_id          0
product_id        0
quantity          0
unit_price_inr    0
discount_pct      0
line_sales_inr    0
line_cost_inr     0
dtype: int64

In [85]:
# check for zeros 
print((order_items == 0).sum())

order_item_id         0
order_id              0
product_id            0
quantity              0
unit_price_inr        0
discount_pct      13130
line_sales_inr        0
line_cost_inr         0
dtype: int64

In [86]:
(order_items).describe().T

                  count           mean          std      min      25%       50%       75%       max
order_item_id   30931.0  105466.000000  8929.154925  90001.0  97733.5  105466.0  113198.5  120931.0
order_id        30931.0   60015.189131  5774.888272  50001.0  55026.5   60021.0   65012.5   70000.0
product_id      30931.0   20749.110116   430.796125  20001.0  20375.0   20748.0   21118.0   21500.0
quantity        30931.0       1.446445     0.731315      1.0      1.0       1.0       2.0       4.0
unit_price_inr  30931.0    1719.945298  1280.141574    178.0    881.0    1347.0    2157.0   13516.0
discount_pct    30931.0       6.935599     7.557230      0.0      0.0       5.0      10.0      25.0
line_sales_inr  30931.0    2312.512198  2269.324138    133.5    976.6    1647.0    2799.9   54064.0
line_cost_inr   30931.0    1739.636126  1769.298085    118.0    723.0    1218.0    2090.0   42020.0

In [87]:
expected_sales = (
    order_items['quantity']
    * order_items['unit_price_inr']
    * (1 - order_items['discount_pct'] / 100)
)

order_items[
    ~np.isclose(
        order_items['line_sales_inr'],
        expected_sales,
        atol=0.01
    )
]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price_inr, discount_pct, line_sales_inr, line_cost_inr]
Index: []

# payments Analysis

In [88]:
print(payments.head())

   payment_id  order_id payment_date    payment_method payment_status  payment_amount_inr
0      120001     50001   2026-04-27        Debit Card        Pending             5553.75
1      120002     50002   2025-05-22  Cash on Delivery           Paid             6894.51
2      120003     50003   2024-10-29            Wallet           Paid            15031.48
3      120004     50004   2024-03-22       Net Banking           Paid            11210.13
4      120005     50005   2024-10-28               UPI           Paid            15207.60

In [89]:
print(payments.shape)

(20000, 6)

In [90]:
print(payments.info())

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   payment_id          20000 non-null  int64
 1   order_id            20000 non-null  int64
 2   payment_date        20000 non-null  str
 3   payment_method      20000 non-null  str
 4   payment_status      20000 non-null  str
 5   payment_amount_inr  20000 non-null  float64
dtypes: float64(1), int64(2), str(3)
memory usage: 937.6 KB
None

In [91]:
print(payments.isnull().sum())

payment_id            0
order_id              0
payment_date          0
payment_method        0
payment_status        0
payment_amount_inr    0
dtype: int64

In [92]:
print(payments.duplicated().sum())

0

In [93]:
# check for Text consistency
print(payments["payment_method"].unique())
print(payments["payment_method"].value_counts(dropna=False))

<StringArray>
['Debit Card', 'Cash on Delivery', 'Wallet', 'Net Banking', 'UPI', 'Credit Card']
Length: 6, dtype: str
payment_method
UPI                 6933
Credit Card         3928
Debit Card          3239
Cash on Delivery    2397
Net Banking         2114
Wallet              1389
Name: count, dtype: int64

In [94]:
# check for text consistency 
print(payments["payment_status"].unique())
print(payments["payment_status"].value_counts(dropna=False))

<StringArray>
['Pending', 'Paid', 'Refunded', 'Failed']
Length: 4, dtype: str
payment_status
Paid        17563
Failed       1065
Refunded      765
Pending       607
Name: count, dtype: int64

In [95]:
# check for leading and trailing space 

print("payment_method with leading & trailing spaces")
print(payments[payments["payment_method"] != payments["payment_method"].str.strip().str.title()])

print("\npayment_status with leading & trailing spaces")
print(payments[payments["payment_status"] != payments["payment_status"].str.strip().str.title()])

payment_method with leading & trailing spaces

       payment_id  order_id payment_date    payment_method payment_status  payment_amount_inr
1          120002     50002   2025-05-22  Cash on Delivery           Paid             6894.51
4          120005     50005   2024-10-28               UPI           Paid            15207.60
8          120009     50009   2026-06-21               UPI           Paid            16022.05
11         120012     50012   2025-09-16               UPI           Paid            29237.03
13         120014     50014   2026-06-16  Cash on Delivery           Paid            29291.82
...           ...       ...          ...               ...            ...                 ...
19990      139991     69991   2025-07-01               UPI           Paid            21987.05
19991      139992     69992   2024-10-20               UPI           Paid            19226.63
19993      139994     69994   2026-07-22               UPI           Paid            25959.35
19995      139996     69996   2025-08-28  Cash on Delivery       Refunded            24579.18
19998      139999     69999   2025-02-13               UPI           Paid             1142.84

[9330 rows x 6 columns]

payment_status with leading & trailing spaces
Empty DataFrame
Columns: [payment_id, order_id, payment_date, payment_method, payment_status, payment_amount_inr]
Index: []

In [96]:
# check for multiple spaces inside Text

print("payment_method with multiple inside spaces")
print(payments[payments["payment_method"].str.contains(r"\s{2,}", na=False)])

print("\npayment_status with multiple inside spaces")
print(payments[payments["payment_status"].str.contains(r"\s{2,}", na=False)])

payment_method with multiple inside spaces
Empty DataFrame
Columns: [payment_id, order_id, payment_date, payment_method, payment_status, payment_amount_inr]
Index: []

payment_status with multiple inside spaces
Empty DataFrame
Columns: [payment_id, order_id, payment_date, payment_method, payment_status, payment_amount_inr]
Index: []

In [97]:
print(payments["payment_date"].dtype)

str

In [98]:
print("earlist payment_date:", payments["payment_date"].min())
print("latest payment_date:", payments["payment_date"].max())

earlist payment_date: 2024-01-01
latest payment_date: 2026-08-30

In [99]:
print(payments["payment_date"].describe())

count          20000
unique           973
top       2024-12-22
freq              37
Name: payment_date, dtype: object

In [100]:
payments[payments["payment_amount_inr"] < 0].count()

payment_id            0
order_id              0
payment_date          0
payment_method        0
payment_status        0
payment_amount_inr    0
dtype: int64

In [101]:
(payments == 0).sum()

payment_id            0
order_id              0
payment_date          0
payment_method        0
payment_status        0
payment_amount_inr    0
dtype: int64

In [102]:
payments.describe().T

                      count           mean          std        min         25%         50%          75%        max
payment_id          20000.0  130000.500000  5773.647028  120001.00  125000.750  130000.500  135000.2500  140000.00
order_id            20000.0   60000.500000  5773.647028   50001.00   55000.750   60000.500   65000.2500   70000.00
payment_amount_inr  20000.0   15102.824612  8596.189049     304.51    7576.435   15114.235   22567.7925   29999.59

cleaning payments

In [103]:
# standerdize payment_method
payments["payment_method"] = payments["payment_method"].str.strip().str.title()

In [104]:
# set data type of payment_date
payments["payment_date"] = pd.to_datetime(payments["payment_date"],dayfirst=True)
print(payments["payment_date"].dtype)

datetime64[us]

C:\Users\user\AppData\Local\Temp\ipykernel_8564\1563622542.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  payments["payment_date"] = pd.to_datetime(payments["payment_date"],dayfirst=True)

# shipping Analysis

In [105]:
# shipping = pd.read_csv("data/shipping.csv")

In [106]:
print(shipping.head())

   shipping_id  order_id  shipping_location_id courier_partner shipping_date expected_delivery_date actual_delivery_date delivery_status
0       150001     50001                    28            DTDC    2026-04-27             2026-04-29           2026-04-29       Delivered
1       150002     50002                    39       Delhivery    2025-05-23             2025-05-26                  NaN        Returned
2       150003     50003                     6        BlueDart    2024-10-30             2024-11-04           2024-11-06       Delivered
3       150004     50004                    64        BlueDart    2024-03-22             2024-03-26           2024-03-25       Delivered
4       150005     50005                    41    Ecom Express    2024-10-29             2024-11-03           2024-11-03       Delivered

In [107]:
print(shipping.shape)

(20000, 8)

In [108]:
print(shipping.info())

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   shipping_id             20000 non-null  int64
 1   order_id                20000 non-null  int64
 2   shipping_location_id    20000 non-null  int64
 3   courier_partner         20000 non-null  str
 4   shipping_date           20000 non-null  str
 5   expected_delivery_date  20000 non-null  str
 6   actual_delivery_date    15574 non-null  str
 7   delivery_status         20000 non-null  str
dtypes: int64(3), str(5)
memory usage: 1.2 MB
None

In [109]:
print(shipping.isnull().sum())

shipping_id                  0
order_id                     0
shipping_location_id         0
courier_partner              0
shipping_date                0
expected_delivery_date       0
actual_delivery_date      4426
delivery_status              0
dtype: int64

In [110]:
print(shipping.duplicated().sum())

0

In [111]:
# check for text consistency in courier_partner

print(shipping["courier_partner"].unique())
print(shipping["courier_partner"].value_counts(dropna=False))

<StringArray>
['DTDC', 'Delhivery', 'BlueDart', 'Ecom Express', 'XpressBees']
Length: 5, dtype: str
courier_partner
BlueDart        4077
Ecom Express    4040
Delhivery       4009
DTDC            3988
XpressBees      3886
Name: count, dtype: int64

In [112]:
# check for text consistency in delievery_status

print(shipping["delivery_status"].unique())
print(shipping["delivery_status"].value_counts(dropna=False))

<StringArray>
['Delivered', 'Returned', 'In Transit', 'Delayed', 'delivered', 'In transit ', 'returned', ' delayed']
Length: 8, dtype: str
delivery_status
Delivered      15510
In Transit      2407
Delayed         1208
Returned         795
delivered         64
In transit         9
 delayed           4
returned           3
Name: count, dtype: int64

In [113]:
# check for leading & trailing spaces 

print("courier_partner with leading & trailing spaces")
print(shipping[shipping["courier_partner"] != shipping["courier_partner"]])

print("\ndelivery_status with leading  & trailing spaces")
print(shipping[shipping["delivery_status"] != shipping["delivery_status"]])

courier_partner with leading & trailing spaces
Empty DataFrame
Columns: [shipping_id, order_id, shipping_location_id, courier_partner, shipping_date, expected_delivery_date, actual_delivery_date, delivery_status]
Index: []

delivery_status with leading  & trailing spaces
Empty DataFrame
Columns: [shipping_id, order_id, shipping_location_id, courier_partner, shipping_date, expected_delivery_date, actual_delivery_date, delivery_status]
Index: []

In [114]:
# check for inside multiple spaces

print("courier_partner with miltiple inside spaces")
print(shipping[shipping["courier_partner"].str.contains(r"\s{2,}", na=False)])

print("\ndelivery_status with multiple inside spaces")
print(shipping[shipping["delivery_status"].str.contains(r"\s{2,}", na=False)])

courier_partner with miltiple inside spaces
Empty DataFrame
Columns: [shipping_id, order_id, shipping_location_id, courier_partner, shipping_date, expected_delivery_date, actual_delivery_date, delivery_status]
Index: []

delivery_status with multiple inside spaces

Empty DataFrame
Columns: [shipping_id, order_id, shipping_location_id, courier_partner, shipping_date, expected_delivery_date, actual_delivery_date, delivery_status]
Index: []

In [115]:
print(shipping["shipping_date"].dtype)
print(shipping["expected_delivery_date"].dtype)
print(shipping["actual_delivery_date"].dtype)

str
str
str

In [116]:
# check for earlist & latest date in shipping date 

print("earliest date in shippping_date:", shipping["shipping_date"].min())
print("latest date in shipping_date:", shipping["shipping_date"].max())

earliest date in shippping_date: 2024-01-01
latest date in shipping_date: 2026-08-30

In [117]:
# check for earliest & latest date in expected_delivey_date

print("earliest date in expected_shipping_date", shipping["expected_delivery_date"].min())
print("latest date in expected_shipping_date", shipping["expected_delivery_date"].max())

earliest date in expected_shipping_date 2024-01-04
latest date in expected_shipping_date 2026-09-04

In [118]:
# check for earliest & latest date in actual_delivery_date

print("ealriest date in actual_delivery_date", shipping["actual_delivery_date"].min())
print("latest date in actual_delivery_date", shipping["actual_delivery_date"].max())

ealriest date in actual_delivery_date 2024-01-04
latest date in actual_delivery_date 2026-09-05

In [119]:
shipping[shipping["actual_delivery_date"].isna()]["delivery_status"].value_counts(dropna=False)

delivery_status
In Transit     2407
Delayed        1208
Returned        795
In transit        9
 delayed          4
returned          3
Name: count, dtype: int64

cleaning shipping

In [120]:
# Standerdize delivery_status

shipping["delivery_status"] = shipping["delivery_status"].str.strip().str.title()
print(shipping["delivery_status"].value_counts(dropna=False))

delivery_status
Delivered     15574
In Transit     2416
Delayed        1212
Returned        798
Name: count, dtype: int64

In [121]:
''' Actual delivery date : 4426 NULLS values were found. These were retained because the corresponding delivery 
    status were in Transit,Delayed or Returned, where an actual delivery date may not be applicable.'''

' Actual delivery date : 4426 NULLS values were found. These were retained because the corresponding delivery \n    status were in Transit,Delayed or Returned, where an actual delivery date may not be applicable.'

In [122]:
# covert datatype of shipping_date
shipping["shipping_date"]= pd.to_datetime(shipping["shipping_date"], dayfirst=True)
print(shipping["shipping_date"].dtype)

datetime64[us]

C:\Users\user\AppData\Local\Temp\ipykernel_8564\1653196421.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  shipping["shipping_date"]= pd.to_datetime(shipping["shipping_date"], dayfirst=True)

In [123]:
# convert datatype of expected_delivery_date
shipping["expected_delivery_date"] = pd.to_datetime(shipping["expected_delivery_date"], dayfirst=True)
print(shipping["expected_delivery_date"].dtype)

datetime64[us]

C:\Users\user\AppData\Local\Temp\ipykernel_8564\1072882813.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  shipping["expected_delivery_date"] = pd.to_datetime(shipping["expected_delivery_date"], dayfirst=True)

In [124]:
# convert datatype of actual_delivery_date
shipping["actual_delivery_date"] = pd.to_datetime(shipping["actual_delivery_date"], dayfirst=True)
print(shipping["actual_delivery_date"].dtype)

datetime64[us]

C:\Users\user\AppData\Local\Temp\ipykernel_8564\3790520988.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  shipping["actual_delivery_date"] = pd.to_datetime(shipping["actual_delivery_date"], dayfirst=True)

# returns Analysis

In [125]:
print(returns.head())

   return_id  order_item_id return_date  return_reason return_status  refund_amount_inr
0     180001          98402  2025-12-13     Wrong Item      Approved             699.56
1     180002         110171  2025-04-23  Quality Issue      Refunded            7997.24
2     180003         117357  2026-07-19     Size Issue      Refunded             592.24
3     180004         119983  2026-03-24        Damaged      Rejected            1134.57
4     180005         120759  2026-06-11  Quality Issue      Approved             997.01

In [126]:
print(returns.shape)

(3500, 6)

In [127]:
print(returns.info())

<class 'pandas.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   return_id          3500 non-null   int64
 1   order_item_id      3500 non-null   int64
 2   return_date        3500 non-null   str
 3   return_reason      3500 non-null   str
 4   return_status      3500 non-null   str
 5   refund_amount_inr  3500 non-null   float64
dtypes: float64(1), int64(2), str(3)
memory usage: 164.2 KB
None

In [128]:
print(returns.isnull().sum())

return_id            0
order_item_id        0
return_date          0
return_reason        0
return_status        0
refund_amount_inr    0
dtype: int64

In [129]:
print(returns.duplicated().sum())

0

In [130]:
# check for text consistency in return_reason

print(returns["return_reason"].unique())
print(returns["return_reason"].value_counts())

<StringArray>
['Wrong Item', 'Quality Issue', 'Size Issue', 'Damaged', 'Changed Mind']
Length: 5, dtype: str
return_reason
Size Issue       967
Quality Issue    826
Damaged          642
Changed Mind     549
Wrong Item       516
Name: count, dtype: int64

In [131]:
# check for text consistency in return_status

print(returns["return_status"].unique())
print(returns["return_status"].value_counts())

<StringArray>
['Approved', 'Refunded', 'Rejected']
Length: 3, dtype: str
return_status
Refunded    1766
Approved    1411
Rejected     323
Name: count, dtype: int64

In [132]:
# check for leading & trailing spaces 
print("return_reason with leading & trailing spaces")
print(returns[returns["return_reason"] != returns["return_reason"].str.strip()])

print("\nreturn_status with leading & trailing spaces")
print(returns[returns["return_status"] != returns["return_status"].str.strip()])

return_reason with leading & trailing spaces
Empty DataFrame
Columns: [return_id, order_item_id, return_date, return_reason, return_status, refund_amount_inr]
Index: []

return_status with leading & trailing spaces
Empty DataFrame
Columns: [return_id, order_item_id, return_date, return_reason, return_status, refund_amount_inr]
Index: []

In [133]:
# checks for multiple spaces inside 

print("return_reason with inside multiple spaces")
print(returns[returns["return_reason"].str.strip().str.contains(r"\s{2,}", na=False)])

print("\nreturn_status with inside multiple spaaces")
print(returns[returns["return_status"].str.strip().str.contains(r"\s{2,}", na=False)])

return_reason with inside multiple spaces
Empty DataFrame
Columns: [return_id, order_item_id, return_date, return_reason, return_status, refund_amount_inr]
Index: []

return_status with inside multiple spaaces
Empty DataFrame
Columns: [return_id, order_item_id, return_date, return_reason, return_status, refund_amount_inr]
Index: []

In [134]:
print(returns["return_date"].dtype)

str

In [135]:
# ealiest & latest date in return_date

print("earliest_date in return_date:", returns["return_date"].min())
print("latest date in return_date:", returns["return_date"].max())

earliest_date in return_date: 2024-01-07
latest date in return_date: 2026-09-19

In [136]:
print(returns["return_date"].describe())

count           3500
unique           947
top       2026-02-21
freq              11
Name: return_date, dtype: object

Cleaning returns

In [137]:
# convert datatype of return_date
returns["return_date"] = pd.to_datetime(returns["return_date"], dayfirst=True)
print(returns["return_date"].dtype)

datetime64[us]

C:\Users\user\AppData\Local\Temp\ipykernel_8564\2161426373.py:2: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  returns["return_date"] = pd.to_datetime(returns["return_date"], dayfirst=True)

# reviews Analysis

In [138]:
print(reviews.head())

   review_id  order_item_id  customer_id review_date  rating      review_text
0     220001         112648        13450  2025-06-16       5          Average
1     220002          95648        12380  2025-01-06       5          Average
2     220003         109958        12129  2024-03-01       5        Excellent
3     220004         108443        11116  2025-05-14       5  Could be better
4     220005         116837        13191  2026-03-30       4  Could be better

In [139]:
print(reviews.shape)

(8000, 6)

In [140]:
print(reviews.info())

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   review_id      8000 non-null   int64
 1   order_item_id  8000 non-null   int64
 2   customer_id    8000 non-null   int64
 3   review_date    8000 non-null   str
 4   rating         8000 non-null   int64
 5   review_text    7968 non-null   str
dtypes: int64(4), str(2)
memory usage: 375.1 KB
None

In [141]:
print(reviews.isnull().sum())

review_id         0
order_item_id     0
customer_id       0
review_date       0
rating            0
review_text      32
dtype: int64

In [142]:
print(reviews.duplicated().sum())

0

In [143]:
print(reviews["review_text"].unique())
print(reviews["review_text"].value_counts())

<StringArray>
['Average', 'Excellent', 'Could be better', 'Poor quality', 'Very good', 'Good', nan]
Length: 7, dtype: str
review_text
Excellent          1352
Very good          1339
Could be better    1338
Average            1337
Good               1308
Poor quality       1294
Name: count, dtype: int64

In [144]:
# check for leading & trailing spaces 

print("review_text with leading & trailing spaces")
print(reviews[reviews["review_text"] != reviews["review_text"].str.strip()])

review_text with leading & trailing spaces
      review_id  order_item_id  customer_id review_date  rating review_text
66       220067         100139        10932  2024-06-06       5         NaN
647      220648          97072        14828  2026-03-22       5         NaN
750      220751          99572        11061  2025-11-20       4         NaN
783      220784         116869        14999  2024-06-22       5         NaN
828      220829         101583        12775  2024-06-24       5         NaN
1262     221263          94395        10156  2024-10-31       5         NaN
1288     221289         111855        11328  2025-02-03       4         NaN
1561     221562         109393        12943  2026-08-08       5         NaN
2424     222425          99886        12425  2024-11-06       3         NaN
2662     222663         120530        11472  2024-08-21       4         NaN
2666     222667         118550        14425  2026-01-19       2         NaN
2704     222705          91752        13908  2025-11-29       5         NaN
3378     223379         102714        12128  2024-07-18       5         NaN
3699     223700          98584        12027  2026-06-25       3         NaN
3772     223773         115534        11475  2026-03-24       5         NaN
3945     223946         106113        12867  2026-07-24       5         NaN
4065     224066          91445        13109  2025-03-26       5         NaN
4244     224245         101909        13193  2025-08-03       4         NaN
4425     224426         117880        10868  2024-10-06       4         NaN
4710     224711         110220        14659  2025-05-04       3         NaN
4908     224909         120049        14987  2025-04-26       2         NaN
5358     225359         114344        11140  2024-02-28       4         NaN
5373     225374          98276        13572  2025-09-26       5         NaN
5496     225497          95139        12999  2025-01-24       5         NaN
5516     225517          94682        13439  2025-10-24       4         NaN
5529     225530         108399        10440  2026-04-10       5         NaN
6254     226255          95749        13665  2025-05-30       3         NaN
6429     226430          99127        11321  2024-10-24       5         NaN
6613     226614         112102        14185  2025-02-27       5         NaN
7389     227390         106636        14266  2026-03-25       1         NaN
7492     227493         101234        12359  2024-04-24       3         NaN
7733     227734         116501        11460  2024-06-01       5         NaN

In [145]:
# checks for multiple spaces inside 
print("review_text with miutiple spaces inside")
print(reviews[reviews["review_text"].str.strip().str.contains(r"\s{2,}", na=False)])

review_text with miutiple spaces inside
Empty DataFrame
Columns: [review_id, order_item_id, customer_id, review_date, rating, review_text]
Index: []

In [146]:
print(reviews["review_date"].dtype)

str

In [147]:
# check for ealiest & latest review_date

print("earliest date in review_date:", reviews["review_date"].min())
print("latest date in review_date", reviews["review_date"].max())

earliest date in review_date: 2024-01-01
latest date in review_date 2026-08-27

In [148]:
reviews[reviews["review_text"].isna()]["rating"].value_counts(dropna=False)

rating
5    17
4     7
3     5
2     2
1     1
Name: count, dtype: int64

In [149]:
reviews[reviews['review_text'].isna()][
    ['review_id', 'order_item_id', 'customer_id', 'rating']
]

      review_id  order_item_id  customer_id  rating
66       220067         100139        10932       5
647      220648          97072        14828       5
750      220751          99572        11061       4
783      220784         116869        14999       5
828      220829         101583        12775       5
1262     221263          94395        10156       5
1288     221289         111855        11328       4
1561     221562         109393        12943       5
2424     222425          99886        12425       3
2662     222663         120530        11472       4
2666     222667         118550        14425       2
2704     222705          91752        13908       5
3378     223379         102714        12128       5
3699     223700          98584        12027       3
3772     223773         115534        11475       5
3945     223946         106113        12867       5
4065     224066          91445        13109       5
4244     224245         101909        13193       4
4425     224426         117880        10868       4
4710     224711         110220        14659       3
4908     224909         120049        14987       2
5358     225359         114344        11140       4
5373     225374          98276        13572       5
5496     225497          95139        12999       5
5516     225517          94682        13439       4
5529     225530         108399        10440       5
6254     226255          95749        13665       3
6429     226430          99127        11321       5
6613     226614         112102        14185       5
7389     227390         106636        14266       1
7492     227493         101234        12359       3
7733     227734         116501        11460       5

In [150]:
# check for maximum and minimum rating 

print("minimum rating in rating:", reviews["rating"].min())
print("maximum rating in rating:", reviews["rating"].max())

minimum rating in rating: 1
maximum rating in rating: 5

Cleaning reviews

In [151]:
'''32 reviews have missing review_text, while all corresponding records contain a rating.
   These were retained as NULL because written review text is optional.'''

'32 reviews have missing review_text, while all corresponding records contain a rating.\n   These were retained as NULL because written review text is optional.'

In [152]:
# removing leading & trailing spaces from review_text
reviews["review_text"] = reviews["review_text"].str.strip()

In [153]:
reviews[
    reviews["review_text"].notna() &
    (reviews["review_text"] != reviews["review_text"].str.strip())
]

Empty DataFrame
Columns: [review_id, order_item_id, customer_id, review_date, rating, review_text]
Index: []

In [154]:
# convert dayatype of review_date

reviews["review_date"] = pd.to_datetime(reviews["review_date"], dayfirst=True)
print(reviews["review_date"].dtype)

datetime64[us]

C:\Users\user\AppData\Local\Temp\ipykernel_8564\1635729189.py:3: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  reviews["review_date"] = pd.to_datetime(reviews["review_date"], dayfirst=True)

# Primary & foreign Key Validation

In [155]:
tables = {
    "customers": customers,
    "products" : products,
    "orders" : orders,
    "order_item" : order_items,
    "payments" : payments,
    "shipping" : shipping,
    "reviews" : reviews
}

pk_columns = {
    "customers": "customer_id",
    "products" : "product_id",
    "orders" : "order_id",
    "order_item": "order_item_id",
    "payments" : "payment_id",
    "shipping" : "shipping_id",
    "reviews" : "review_id"
}

# check for nulls in primary key 

for table_name, df in tables.items():
    pk = pk_columns[table_name]
    print(f"{table_name} → NULL PKs:", df[pk].isna().sum())

customers → NULL PKs: 0
products → NULL PKs: 0
orders → NULL PKs: 0
order_item → NULL PKs: 0
payments → NULL PKs: 0
shipping → NULL PKs: 0
reviews → NULL PKs: 0

In [156]:
# check for duplicate in primary keys

for table_name, df in tables.items():
    pk = pk_columns[table_name]
    print(f"{table_name} → Duplicate PKs:", df[pk].duplicated().sum())

customers → Duplicate PKs: 0
products → Duplicate PKs: 0
orders → Duplicate PKs: 0
order_item → Duplicate PKs: 0
payments → Duplicate PKs: 0
shipping → Duplicate PKs: 0
reviews → Duplicate PKs: 0

foreign key Validation

In [157]:
# 1. Customers → Locations
print("Customers → Locations")
print(customers["location_id"].isin(locations["location_id"]).value_counts())

Customers → Locations
location_id
True    5000
Name: count, dtype: int64

In [158]:
# 2. Orders → Customers
print("Orders → Customers")
print(orders["customer_id"].isin(customers["customer_id"]).value_counts())

Orders → Customers
customer_id
True    20000
Name: count, dtype: int64

In [159]:
# 3. Order Items → Orders
print("Order Items → Orders")
print(order_items["order_id"].isin(orders["order_id"]).value_counts())

Order Items → Orders
order_id
True    30931
Name: count, dtype: int64

In [160]:
# 4. Order Items → Products
print("Order Items → Products")
print(order_items["product_id"].isin(products["product_id"]).value_counts())

Order Items → Products
product_id
True    30931
Name: count, dtype: int64

In [161]:
# 5. Payments → Orders
print("Payments → Orders")
print(payments["order_id"].isin(orders["order_id"]).value_counts())

Payments → Orders
order_id
True    20000
Name: count, dtype: int64

In [162]:
# 6. Shipping → Orders
print("Shipping → Orders")
print(shipping["order_id"].isin(orders["order_id"]).value_counts())

Shipping → Orders
order_id
True    20000
Name: count, dtype: int64

In [163]:

# 7. Shipping → Locations
print("Shipping → Locations")
print(shipping["shipping_location_id"].isin(locations["location_id"]).value_counts())

Shipping → Locations
shipping_location_id
True    20000
Name: count, dtype: int64

In [164]:

# 9. Reviews → Order Items
print("Reviews → Order Items")
print(reviews["order_item_id"].isin(order_items["order_item_id"]).value_counts())

Reviews → Order Items
order_item_id
True    8000
Name: count, dtype: int64

In [165]:
# 10. Reviews → Customers
print("Reviews → Customers")
print(reviews["customer_id"].isin(customers["customer_id"]).value_counts())

Reviews → Customers
customer_id
True    8000
Name: count, dtype: int64

# Final check

In [166]:
# FINAL NULL CHECK

for table_name, df in tables.items():
    print(f"{table_name}: {df.isna().sum().sum()} NULL values")

customers: 10 NULL values
products: 0 NULL values
orders: 0 NULL values
order_item: 0 NULL values
payments: 0 NULL values
shipping: 4426 NULL values
reviews: 32 NULL values

In [167]:
# FINAL DUPLICATE CHECK

for table_name, df in tables.items():
    print(f"{table_name}: {df.duplicated().sum()} duplicate rows")

customers: 0 duplicate rows
products: 0 duplicate rows
orders: 0 duplicate rows
order_item: 0 duplicate rows
payments: 0 duplicate rows
shipping: 0 duplicate rows
reviews: 0 duplicate rows

In [168]:
for table_name, df in tables.items():
    print(f"{table_name}: {df.shape[0]} rows × {df.shape[1]} columns")

customers: 5000 rows × 7 columns
products: 1500 rows × 8 columns
orders: 20000 rows × 6 columns
order_item: 30931 rows × 8 columns
payments: 20000 rows × 6 columns
shipping: 20000 rows × 8 columns
reviews: 8000 rows × 6 columns

In [169]:
# FINAL SANITY CHECK

print("===== E-COMMERCE DATASET SANITY CHECK =====\n")

print("Customers:", len(customers))
print("Products:", len(products))
print("Orders:", len(orders))
print("Order Items:", len(order_items))
print("Payments:", len(payments))
print("Shipping:", len(shipping))
print("Returns:", len(returns))
print("Reviews:", len(reviews))
print("Locations:", len(locations))

===== E-COMMERCE DATASET SANITY CHECK =====

Customers: 5000
Products: 1500
Orders: 20000
Order Items: 30931
Payments: 20000
Shipping: 20000
Returns: 3500
Reviews: 8000
Locations: 100

In [170]:
print("\n===== RELATIONSHIP SANITY =====")

print("Unique customers with orders:",
      orders["customer_id"].nunique())

print("Unique products sold:",
      order_items["product_id"].nunique())

print("Orders with payments:",
      payments["order_id"].nunique())

print("Orders with shipping:",
      shipping["order_id"].nunique())

print("Order items returned:",
      returns["order_item_id"].nunique())

print("Order items reviewed:",
      reviews["order_item_id"].nunique())

===== RELATIONSHIP SANITY =====
Unique customers with orders: 4920
Unique products sold: 1500
Orders with payments: 20000
Orders with shipping: 20000
Order items returned: 3500
Order items reviewed: 8000

In [171]:
print("\n===== BUSINESS SANITY =====")

print("Total order quantity:",
      order_items["quantity"].sum())

print("Total sales:",
      order_items["quantity"].mul(order_items["unit_price_inr"]).sum())

print("Average product price:",
      products["unit_price_inr"].mean())

print("Average review rating:",
      reviews["rating"].mean())

===== BUSINESS SANITY =====
Total order quantity: 44740
Total sales: 76913511.0
Average product price: 1720.8146666666667
Average review rating: 3.894625

In [172]:
import os

os.makedirs("clean_data", exist_ok=True)

customers.to_csv(
    "clean_data/customers.csv",
    index=False,
    na_rep="NULL"
)

products.to_csv(
    "clean_data/products.csv",
    index=False,
    na_rep="NULL"
)

orders.to_csv(
    "clean_data/orders.csv",
    index=False,
    na_rep="NULL"
)

order_items.to_csv(
    "clean_data/order_items.csv",
    index=False,
    na_rep="NULL"
)

payments.to_csv(
    "clean_data/payments.csv",
    index=False,
    na_rep="NULL"
)

shipping.to_csv(
    "clean_data/shipping.csv",
    index=False,
    na_rep="NULL"
)

returns.to_csv(
    "clean_data/returns.csv",
    index=False,
    na_rep="NULL"
)

reviews.to_csv(
    "clean_data/reviews.csv",
    index=False,
    na_rep="NULL"
)

locations.to_csv(
    "clean_data/locations.csv",
    index=False,
    na_rep="NULL"
)